// GENERATED by web/scripts/tokens.ts from DESIGN.md. Do not edit;
// change the frontmatter and run `bun web/scripts/tokens.ts`.

package dev.starbridge.app.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp

@Immutable
data class StarbridgeColors(
    val bg: Color,
    val surface: Color,
    val surface2: Color,
    val line: Color,
    val lineStrong: Color,
    val fg: Color,
    val fg2: Color,
    val fg3: Color,
    val accent: Color,
    val accentHi: Color,
    val onAccent: Color,
    val accentSoft: Color,
    val ok: Color,
    val okSoft: Color,
    val warn: Color,
    val warnSoft: Color,
    val bad: Color,
    val badSoft: Color,
    val info: Color,
    val infoSoft: Color,
    val scrim: Color,
)

val LightColors = StarbridgeColors(
    bg = Color(0xFFF4F4F4),
    surface = Color(0xFFFFFFFF),
    surface2 = Color(0xFFEBEBEB),
    line = Color(0xFFE0E0E0),
    lineStrong = Color(0xFFC6C6C6),
    fg = Color(0xFF121212),
    fg2 = Color(0xFF595959),
    fg3 = Color(0xFF8C8C8C),
    accent = Color(0xFFA35F00),
    accentHi = Color(0xFF8A5000),
    onAccent = Color(0xFFFFFFFF),
    accentSoft = Color(0x1AA35F00),
    ok = Color(0xFF595959),
    okSoft = Color(0x1A595959),
    warn = Color(0xFFA35F00),
    warnSoft = Color(0x1AA35F00),
    bad = Color(0xFFC93A2E),
    badSoft = Color(0x1AC93A2E),
    info = Color(0xFF595959),
    infoSoft = Color(0x1A595959),
    scrim = Color(0x66000000),
)

val DarkColors = StarbridgeColors(
    bg = Color(0xFF0C0C0C),
    surface = Color(0xFF171717),
    surface2 = Color(0xFF232323),
    line = Color(0xFF2A2A2A),
    lineStrong = Color(0xFF3B3B3B),
    fg = Color(0xFFF1F1F1),
    fg2 = Color(0xFFA3A3A3),
    fg3 = Color(0xFF6A6A6A),
    accent = Color(0xFFF5A83B),
    accentHi = Color(0xFFFFC067),
    onAccent = Color(0xFF1C1100),
    accentSoft = Color(0x1FF5A83B),
    ok = Color(0xFFA3A3A3),
    okSoft = Color(0x1FA3A3A3),
    warn = Color(0xFFF5A83B),
    warnSoft = Color(0x1FF5A83B),
    bad = Color(0xFFFF6B5F),
    badSoft = Color(0x1FFF6B5F),
    info = Color(0xFFA3A3A3),
    infoSoft = Color(0x1FA3A3A3),
    scrim = Color(0xB3000000),
)

object Spacing {
    val s1 = 4.dp
    val s2 = 8.dp
    val s3 = 12.dp
    val s4 = 16.dp
    val s5 = 20.dp
    val s6 = 24.dp
    val s8 = 32.dp
    val s10 = 40.dp
}

object Radius {
    val xs = 4.dp
    val sm = 8.dp
    val md = 12.dp
    val lg = 16.dp
    val xl = 28.dp
    val pill = 999.dp
}

object Sizes {
    val tap = 48.dp
    val bar = 80.dp
    val rail = 240.dp
    val content = 720.dp
    val track = 10.dp
}

object Motion {
    const val fastMs = 150L
    const val stateMs = 250L
    const val springMs = 350L
}

// The theme passes the bundled faces.
class StarbridgeType(sans: FontFamily, mono: FontFamily) {
    val title = TextStyle(
        fontFamily = sans,
        fontSize = 32.sp,
        fontWeight = FontWeight(500),
        lineHeight = 40.sp,
        letterSpacing = 0.em,
    )
    val heading = TextStyle(
        fontFamily = sans,
        fontSize = 24.sp,
        fontWeight = FontWeight(500),
        lineHeight = 31.992.sp,
        letterSpacing = 0.em,
    )
    val question = TextStyle(
        fontFamily = sans,
        fontSize = 22.sp,
        fontWeight = FontWeight(500),
        lineHeight = 28.006.sp,
        letterSpacing = 0.em,
    )
    val body = TextStyle(
        fontFamily = sans,
        fontSize = 16.sp,
        fontWeight = FontWeight(400),
        lineHeight = 24.sp,
        letterSpacing = 0.031.em,
    )
    val action = TextStyle(
        fontFamily = sans,
        fontSize = 16.sp,
        fontWeight = FontWeight(500),
        lineHeight = 24.sp,
        letterSpacing = 0.009.em,
    )
    val small = TextStyle(
        fontFamily = sans,
        fontSize = 14.sp,
        fontWeight = FontWeight(400),
        lineHeight = 20.006.sp,
        letterSpacing = 0.018.em,
    )
    val figure = TextStyle(
        fontFamily = sans,
        fontSize = 28.sp,
        fontWeight = FontWeight(600),
        lineHeight = 36.008.sp,
        letterSpacing = 0.em,
        fontFeatureSettings = "tnum",
    )
    val machine = TextStyle(
        fontFamily = sans,
        fontSize = 14.sp,
        fontWeight = FontWeight(400),
        lineHeight = 20.006.sp,
        letterSpacing = 0.018.em,
        fontFeatureSettings = "tnum",
    )
    val label = TextStyle(
        fontFamily = sans,
        fontSize = 14.sp,
        fontWeight = FontWeight(500),
        lineHeight = 20.006.sp,
        letterSpacing = 0.007.em,
    )
    val code = TextStyle(
        fontFamily = mono,
        fontSize = 14.sp,
        fontWeight = FontWeight(400),
        lineHeight = 20.006.sp,
        letterSpacing = 0.em,
    )
}
