// GENERATED by web/scripts/tokens.ts from DESIGN.md. Do not edit;
// change the frontmatter and run `bun web/scripts/tokens.ts`.

package dev.starbridge.app.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp

@Immutable
data class StarbridgeColors(
    val bg: Color,
    val surface: Color,
    val surface2: Color,
    val line: Color,
    val lineStrong: Color,
    val fg: Color,
    val fg2: Color,
    val fg3: Color,
    val accent: Color,
    val accentHi: Color,
    val onAccent: Color,
    val accentSoft: Color,
    val ok: Color,
    val okSoft: Color,
    val warn: Color,
    val warnSoft: Color,
    val bad: Color,
    val badSoft: Color,
    val info: Color,
    val infoSoft: Color,
    val scrim: Color,
)

val LightColors = StarbridgeColors(
    bg = Color(0xFFF4F5F8),
    surface = Color(0xFFFFFFFF),
    surface2 = Color(0xFFECEEF3),
    line = Color(0xFFDCDFE7),
    lineStrong = Color(0xFFC3C8D4),
    fg = Color(0xFF141821),
    fg2 = Color(0xFF525A6B),
    fg3 = Color(0xFF818999),
    accent = Color(0xFFB45F06),
    accentHi = Color(0xFF9A4F00),
    onAccent = Color(0xFFFFFFFF),
    accentSoft = Color(0x1AB45F06),
    ok = Color(0xFF1F7A45),
    okSoft = Color(0x1A1F7A45),
    warn = Color(0xFF7D6400),
    warnSoft = Color(0x1F7D6400),
    bad = Color(0xFFC0352B),
    badSoft = Color(0x1AC0352B),
    info = Color(0xFF2A62C9),
    infoSoft = Color(0x1A2A62C9),
    scrim = Color(0x990B0E14),
)

val DarkColors = StarbridgeColors(
    bg = Color(0xFF0B0E14),
    surface = Color(0xFF131823),
    surface2 = Color(0xFF1B2130),
    line = Color(0xFF252C3C),
    lineStrong = Color(0xFF343D52),
    fg = Color(0xFFE8EBF2),
    fg2 = Color(0xFF9AA3B5),
    fg3 = Color(0xFF687186),
    accent = Color(0xFFF5A83B),
    accentHi = Color(0xFFFFC067),
    onAccent = Color(0xFF1A0F00),
    accentSoft = Color(0x1FF5A83B),
    ok = Color(0xFF5CCF8A),
    okSoft = Color(0x1F5CCF8A),
    warn = Color(0xFFE5C454),
    warnSoft = Color(0x1FE5C454),
    bad = Color(0xFFFF7B72),
    badSoft = Color(0x1FFF7B72),
    info = Color(0xFF7AA7FF),
    infoSoft = Color(0x1F7AA7FF),
    scrim = Color(0xA6000000),
)

object Spacing {
    val s1 = 4.dp
    val s2 = 8.dp
    val s3 = 12.dp
    val s4 = 16.dp
    val s5 = 20.dp
    val s6 = 24.dp
    val s8 = 32.dp
    val s10 = 40.dp
}

object Radius {
    val sm = 8.dp
    val md = 14.dp
    val lg = 20.dp
    val pill = 999.dp
}

object Sizes {
    val tap = 48.dp
    val bar = 64.dp
    val rail = 240.dp
    val content = 720.dp
}

object Motion {
    const val fastMs = 150L
    const val stateMs = 250L
}

// The theme passes the bundled faces.
class StarbridgeType(sans: FontFamily, mono: FontFamily) {
    val title = TextStyle(
        fontFamily = sans,
        fontSize = 26.sp,
        fontWeight = FontWeight(600),
        lineHeight = 29.9.sp,
        letterSpacing = -0.025.em,
    )
    val heading = TextStyle(
        fontFamily = sans,
        fontSize = 18.sp,
        fontWeight = FontWeight(600),
        lineHeight = 22.5.sp,
        letterSpacing = -0.015.em,
    )
    val question = TextStyle(
        fontFamily = sans,
        fontSize = 17.sp,
        fontWeight = FontWeight(520),
        lineHeight = 22.95.sp,
        letterSpacing = -0.01.em,
    )
    val body = TextStyle(
        fontFamily = sans,
        fontSize = 15.sp,
        fontWeight = FontWeight(400),
        lineHeight = 22.5.sp,
        letterSpacing = 0.em,
    )
    val action = TextStyle(
        fontFamily = sans,
        fontSize = 15.sp,
        fontWeight = FontWeight(600),
        lineHeight = 18.sp,
        letterSpacing = -0.005.em,
    )
    val small = TextStyle(
        fontFamily = sans,
        fontSize = 13.sp,
        fontWeight = FontWeight(400),
        lineHeight = 18.2.sp,
        letterSpacing = 0.em,
    )
    val figure = TextStyle(
        fontFamily = sans,
        fontSize = 28.sp,
        fontWeight = FontWeight(600),
        lineHeight = 28.sp,
        letterSpacing = -0.02.em,
        fontFeatureSettings = "tnum",
    )
    val machine = TextStyle(
        fontFamily = sans,
        fontSize = 13.sp,
        fontWeight = FontWeight(400),
        lineHeight = 18.2.sp,
        letterSpacing = 0.em,
        fontFeatureSettings = "tnum",
    )
    val label = TextStyle(
        fontFamily = sans,
        fontSize = 13.sp,
        fontWeight = FontWeight(600),
        lineHeight = 16.9.sp,
        letterSpacing = 0.em,
    )
    val code = TextStyle(
        fontFamily = mono,
        fontSize = 13.sp,
        fontWeight = FontWeight(400),
        lineHeight = 19.5.sp,
        letterSpacing = 0.em,
    )
}
