// GENERATED by web/scripts/tokens.ts from DESIGN.md. Do not edit;
// change the frontmatter and run `bun web/scripts/tokens.ts`.

package dev.starbridge.app.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp

@Immutable
data class StarbridgeColors(
    val bg: Color,
    val surface: Color,
    val surface2: Color,
    val line: Color,
    val lineStrong: Color,
    val fg: Color,
    val fg2: Color,
    val fg3: Color,
    val accent: Color,
    val accentHi: Color,
    val onAccent: Color,
    val accentSoft: Color,
    val ok: Color,
    val okSoft: Color,
    val warn: Color,
    val warnSoft: Color,
    val bad: Color,
    val badSoft: Color,
    val info: Color,
    val infoSoft: Color,
    val scrim: Color,
)

val LightColors = StarbridgeColors(
    bg = Color(0xFFF4F4F4),
    surface = Color(0xFFFFFFFF),
    surface2 = Color(0xFFEBEBEB),
    line = Color(0xFFE0E0E0),
    lineStrong = Color(0xFFC6C6C6),
    fg = Color(0xFF121212),
    fg2 = Color(0xFF595959),
    fg3 = Color(0xFF8C8C8C),
    accent = Color(0xFF965700),
    accentHi = Color(0xFF7A4600),
    onAccent = Color(0xFFFFFFFF),
    accentSoft = Color(0x1A965700),
    ok = Color(0xFF595959),
    okSoft = Color(0x1A595959),
    warn = Color(0xFF965700),
    warnSoft = Color(0x1A965700),
    bad = Color(0xFFB8322A),
    badSoft = Color(0x1AB8322A),
    info = Color(0xFF595959),
    infoSoft = Color(0x1A595959),
    scrim = Color(0x66000000),
)

val DarkColors = StarbridgeColors(
    bg = Color(0xFF0C0C0C),
    surface = Color(0xFF171717),
    surface2 = Color(0xFF232323),
    line = Color(0xFF2A2A2A),
    lineStrong = Color(0xFF3B3B3B),
    fg = Color(0xFFF1F1F1),
    fg2 = Color(0xFFA3A3A3),
    fg3 = Color(0xFF6A6A6A),
    accent = Color(0xFFF5A83B),
    accentHi = Color(0xFFFFC067),
    onAccent = Color(0xFF1C1100),
    accentSoft = Color(0x1FF5A83B),
    ok = Color(0xFFA3A3A3),
    okSoft = Color(0x1FA3A3A3),
    warn = Color(0xFFF5A83B),
    warnSoft = Color(0x1FF5A83B),
    bad = Color(0xFFFF6B5F),
    badSoft = Color(0x1FFF6B5F),
    info = Color(0xFFA3A3A3),
    infoSoft = Color(0x1FA3A3A3),
    scrim = Color(0xB3000000),
)

// Each provider's dot, by CodexBar provider id.
val LightProviders: Map<String, Color> = mapOf(
    "abacus" to Color(0xFF0091C5),
    "aiand" to Color(0xFFE25C2B),
    "aixy" to Color(0xFF123650),
    "alibaba" to Color(0xFFE35D00),
    "alibabatokenplan" to Color(0xFFE35D00),
    "amp" to Color(0xFFDC2626),
    "antigravity" to Color(0xFF3C975E),
    "atlascloud" to Color(0xFF5975F5),
    "augment" to Color(0xFF6366F1),
    "azureopenai" to Color(0xFF0078D4),
    "bedrock" to Color(0xFFC37400),
    "bifrost" to Color(0xFF00987B),
    "chutes" to Color(0xFF2F82FD),
    "claude" to Color(0xFFC07154),
    "clawrouter" to Color(0xFF596EF6),
    "clinepass" to Color(0xFF4788DD),
    "coderabbit" to Color(0xFFF04E26),
    "codebuff" to Color(0xFF259B00),
    "codex" to Color(0xFF36929F),
    "commandcode" to Color(0xFFA04DFD),
    "copilot" to Color(0xFFA855F7),
    "cursor" to Color(0xFF009782),
    "deepinfra" to Color(0xFF2A3275),
    "deepseek" to Color(0xFF527DF0),
    "deepgram" to Color(0xFF6467F2),
    "devpass" to Color(0xFF2563EB),
    "devin" to Color(0xFF239969),
    "doubao" to Color(0xFF3370FF),
    "elevenlabs" to Color(0xFF878783),
    "factory" to Color(0xFFE9571C),
    "fireworks" to Color(0xFFEB5410),
    "gemini" to Color(0xFF9975D6),
    "gitkraken" to Color(0xFF179287),
    "grok" to Color(0xFF009976),
    "groq" to Color(0xFFE55935),
    "helmcode" to Color(0xFF4934E1),
    "huggingface" to Color(0xFFA28400),
    "hyper" to Color(0xFFDE3CDF),
    "ibmbob" to Color(0xFF0E61FA),
    "jetbrains" to Color(0xFFF92C94),
    "kilo" to Color(0xFFE0600A),
    "kimi" to Color(0xFFEE512C),
    "kiro" to Color(0xFFC37400),
    "llmman" to Color(0xFF3A9682),
    "llmproxy" to Color(0xFF009968),
    "litellm" to Color(0xFF4884EB),
    "longcat" to Color(0xFFA38400),
    "manus" to Color(0xFF34322D),
    "mimo" to Color(0xFFE35C00),
    "minimax" to Color(0xFFEE512C),
    "mistral" to Color(0xFFF54900),
    "moonshot" to Color(0xFF205DEB),
    "muse" to Color(0xFF0668E1),
    "neuralwatt" to Color(0xFF009B5E),
    "notion" to Color(0xFF337EA9),
    "nous" to Color(0xFFAE7E34),
    "ollama" to Color(0xFF878787),
    "openai" to Color(0xFF0F826E),
    "opencode" to Color(0xFF3B82F6),
    "opencodego" to Color(0xFF3B82F6),
    "openrouter" to Color(0xFF6467F2),
    "perplexity" to Color(0xFF009790),
    "pi" to Color(0xFF7C3AED),
    "poe" to Color(0xFF5D5CDE),
    "qoder" to Color(0xFF009A6A),
    "qwencloud" to Color(0xFF615CED),
    "raycast" to Color(0xFFEB5053),
    "replicate" to Color(0xFF000000),
    "sakana" to Color(0xFF2975DB),
    "stepfun" to Color(0xFF088BE6),
    "sub2api" to Color(0xFF0094A3),
    "synthetic" to Color(0xFF141414),
    "t3chat" to Color(0xFFE55739),
    "typesafe" to Color(0xFF111111),
    "v0" to Color(0xFF111111),
    "venice" to Color(0xFF1D89EE),
    "vercel" to Color(0xFF878787),
    "vertexai" to Color(0xFF4083F2),
    "warp" to Color(0xFF8A82AB),
    "wayfinder" to Color(0xFF009976),
    "windsurf" to Color(0xFF009979),
    "xai" to Color(0xFF86868B),
    "xkiro" to Color(0xFF05996E),
    "zai" to Color(0xFFE45767),
    "zed" to Color(0xFF084EFF),
    "zenmux" to Color(0xFF6C5CE7),
    "zoommate" to Color(0xFF0B5CFF),
)

val DarkProviders: Map<String, Color> = mapOf(
    "abacus" to Color(0xFF38BDF8),
    "aiand" to Color(0xFFE25C2B),
    "aixy" to Color(0xFF4C708D),
    "alibaba" to Color(0xFFFF6A00),
    "alibabatokenplan" to Color(0xFFFF6A00),
    "amp" to Color(0xFFDC2626),
    "antigravity" to Color(0xFF60BA7E),
    "atlascloud" to Color(0xFF5975F5),
    "augment" to Color(0xFF6366F1),
    "azureopenai" to Color(0xFF0078D4),
    "bedrock" to Color(0xFFFF9900),
    "bifrost" to Color(0xFF33C09E),
    "chutes" to Color(0xFF3184FF),
    "claude" to Color(0xFFCC7C5E),
    "clawrouter" to Color(0xFF596EF6),
    "clinepass" to Color(0xFF61A3FA),
    "coderabbit" to Color(0xFFFF5C35),
    "codebuff" to Color(0xFF44FF00),
    "codex" to Color(0xFF49A3B0),
    "commandcode" to Color(0xFFA04DFD),
    "copilot" to Color(0xFFA855F7),
    "cursor" to Color(0xFF00BFA5),
    "deepinfra" to Color(0xFF5B68B1),
    "deepseek" to Color(0xFF527DF0),
    "deepgram" to Color(0xFF6467F2),
    "devpass" to Color(0xFF2563EB),
    "devin" to Color(0xFF46B482),
    "doubao" to Color(0xFF3370FF),
    "elevenlabs" to Color(0xFFEBEBE6),
    "factory" to Color(0xFFFF6B35),
    "fireworks" to Color(0xFFF25B1C),
    "gemini" to Color(0xFFAB87EA),
    "gitkraken" to Color(0xFF179287),
    "grok" to Color(0xFF10A37F),
    "groq" to Color(0xFFF56844),
    "helmcode" to Color(0xFF5A51FC),
    "huggingface" to Color(0xFFFFD21E),
    "hyper" to Color(0xFFFF60FF),
    "ibmbob" to Color(0xFF0E61FA),
    "jetbrains" to Color(0xFFFF3399),
    "kilo" to Color(0xFFF27027),
    "kimi" to Color(0xFFFE603C),
    "kiro" to Color(0xFFFF9900),
    "llmman" to Color(0xFF6CC5B0),
    "llmproxy" to Color(0xFF24B47E),
    "litellm" to Color(0xFF4C89F0),
    "longcat" to Color(0xFFFFD100),
    "manus" to Color(0xFF6F6C67),
    "mimo" to Color(0xFFFF6900),
    "minimax" to Color(0xFFFE603C),
    "mistral" to Color(0xFFFF500F),
    "moonshot" to Color(0xFF2462F0),
    "muse" to Color(0xFF0668E1),
    "neuralwatt" to Color(0xFF38D98C),
    "notion" to Color(0xFF337EA9),
    "nous" to Color(0xFFD6A55C),
    "ollama" to Color(0xFF888888),
    "openai" to Color(0xFF0F826E),
    "opencode" to Color(0xFF3B82F6),
    "opencodego" to Color(0xFF3B82F6),
    "openrouter" to Color(0xFF6467F2),
    "perplexity" to Color(0xFF20B2AA),
    "pi" to Color(0xFF8242F4),
    "poe" to Color(0xFF5D5CDE),
    "qoder" to Color(0xFF10B981),
    "qwencloud" to Color(0xFF615CED),
    "raycast" to Color(0xFFFF6363),
    "replicate" to Color(0xFF6D6D6D),
    "sakana" to Color(0xFF2975DB),
    "stepfun" to Color(0xFF2196F2),
    "sub2api" to Color(0xFF2DC6D8),
    "synthetic" to Color(0xFF6D6D6D),
    "t3chat" to Color(0xFFF56647),
    "typesafe" to Color(0xFF6E6E6E),
    "v0" to Color(0xFF6E6E6E),
    "venice" to Color(0xFF3399FF),
    "vercel" to Color(0xFFFFFFFF),
    "vertexai" to Color(0xFF4285F4),
    "warp" to Color(0xFF938BB4),
    "wayfinder" to Color(0xFF10A37F),
    "windsurf" to Color(0xFF34E8BB),
    "xai" to Color(0xFF8E8E93),
    "xkiro" to Color(0xFF52C99B),
    "zai" to Color(0xFFE85A6A),
    "zed" to Color(0xFF1A5CFF),
    "zenmux" to Color(0xFF6C5CE7),
    "zoommate" to Color(0xFF105EFF),
)

object Spacing {
    val s1 = 4.dp
    val s2 = 8.dp
    val s3 = 12.dp
    val s4 = 16.dp
    val s5 = 20.dp
    val s6 = 24.dp
    val s8 = 32.dp
    val s10 = 40.dp
}

object Radius {
    val xs = 4.dp
    val sm = 8.dp
    val md = 12.dp
    val lg = 16.dp
    val xl = 28.dp
    val pill = 999.dp
}

object Sizes {
    val tap = 48.dp
    val bar = 80.dp
    val rail = 240.dp
    val content = 720.dp
    val track = 10.dp
    val trackDense = 6.dp
    val tick = 2.dp
    val cap = 4.dp
    val hatch = 6.dp
    val media = 360.dp
    val page = 1040.dp
    val shot = 320.dp
}

object Motion {
    const val fastMs = 150L
    const val stateMs = 250L
    const val springMs = 350L
}

// The theme passes the bundled faces.
class StarbridgeType(sans: FontFamily, mono: FontFamily) {
    val hero = TextStyle(
        fontFamily = sans,
        fontSize = 72.sp,
        fontWeight = FontWeight(500),
        lineHeight = 76.sp,
        letterSpacing = -0.025.em,
    )
    val display = TextStyle(
        fontFamily = sans,
        fontSize = 45.sp,
        fontWeight = FontWeight(500),
        lineHeight = 52.sp,
        letterSpacing = 0.em,
    )
    val title = TextStyle(
        fontFamily = sans,
        fontSize = 36.sp,
        fontWeight = FontWeight(500),
        lineHeight = 44.sp,
        letterSpacing = 0.em,
    )
    val heading = TextStyle(
        fontFamily = sans,
        fontSize = 24.sp,
        fontWeight = FontWeight(500),
        lineHeight = 32.sp,
        letterSpacing = 0.em,
    )
    val question = TextStyle(
        fontFamily = sans,
        fontSize = 22.sp,
        fontWeight = FontWeight(500),
        lineHeight = 28.sp,
        letterSpacing = 0.em,
    )
    val subtitle = TextStyle(
        fontFamily = sans,
        fontSize = 18.sp,
        fontWeight = FontWeight(500),
        lineHeight = 24.sp,
        letterSpacing = 0.em,
    )
    val lead = TextStyle(
        fontFamily = sans,
        fontSize = 19.sp,
        fontWeight = FontWeight(400),
        lineHeight = 28.sp,
        letterSpacing = 0.em,
    )
    val prose = TextStyle(
        fontFamily = sans,
        fontSize = 17.sp,
        fontWeight = FontWeight(400),
        lineHeight = 26.sp,
        letterSpacing = 0.em,
    )
    val body = TextStyle(
        fontFamily = sans,
        fontSize = 16.sp,
        fontWeight = FontWeight(400),
        lineHeight = 24.sp,
        letterSpacing = 0.em,
    )
    val action = TextStyle(
        fontFamily = sans,
        fontSize = 16.sp,
        fontWeight = FontWeight(500),
        lineHeight = 24.sp,
        letterSpacing = 0.em,
    )
    val reading = TextStyle(
        fontFamily = sans,
        fontSize = 15.sp,
        fontWeight = FontWeight(400),
        lineHeight = 24.sp,
        letterSpacing = 0.em,
    )
    val small = TextStyle(
        fontFamily = sans,
        fontSize = 14.sp,
        fontWeight = FontWeight(400),
        lineHeight = 20.sp,
        letterSpacing = 0.em,
    )
    val label = TextStyle(
        fontFamily = sans,
        fontSize = 14.sp,
        fontWeight = FontWeight(500),
        lineHeight = 20.sp,
        letterSpacing = 0.em,
    )
    val machine = TextStyle(
        fontFamily = sans,
        fontSize = 14.sp,
        fontWeight = FontWeight(400),
        lineHeight = 20.sp,
        letterSpacing = 0.em,
        fontFeatureSettings = "tnum",
    )
    val meta = TextStyle(
        fontFamily = sans,
        fontSize = 13.sp,
        fontWeight = FontWeight(400),
        lineHeight = 20.sp,
        letterSpacing = 0.em,
        fontFeatureSettings = "tnum",
    )
    val caption = TextStyle(
        fontFamily = sans,
        fontSize = 12.sp,
        fontWeight = FontWeight(400),
        lineHeight = 16.sp,
        letterSpacing = 0.em,
    )
    val key = TextStyle(
        fontFamily = sans,
        fontSize = 11.sp,
        fontWeight = FontWeight(500),
        lineHeight = 16.sp,
        letterSpacing = 0.em,
    )
    val figure = TextStyle(
        fontFamily = sans,
        fontSize = 24.sp,
        fontWeight = FontWeight(600),
        lineHeight = 32.sp,
        letterSpacing = 0.em,
        fontFeatureSettings = "tnum",
    )
    val code = TextStyle(
        fontFamily = mono,
        fontSize = 14.sp,
        fontWeight = FontWeight(400),
        lineHeight = 20.sp,
        letterSpacing = 0.em,
    )
    val command = TextStyle(
        fontFamily = mono,
        fontSize = 18.sp,
        fontWeight = FontWeight(400),
        lineHeight = 28.sp,
        letterSpacing = 0.em,
    )
}
