// Emits the design tokens from the YAML frontmatter of ../../DESIGN.md, the
// single source of truth, for both clients:
//
//   web/src/styles/tokens.css   custom properties, light and dark
//   web/src/styles/type.css     one .t-<role> class per typography role
//   android/.../ui/theme/Tokens.kt
//
//   bun web/scripts/tokens.ts          rewrite all three
//   bun web/scripts/tokens.ts --check  exit 1 if any is stale (CI)

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "../..");
const DESIGN_MD = resolve(ROOT, "DESIGN.md");
const KOTLIN_PACKAGE = "dev.starbridge.app.ui.theme";
const OUT = {
  css: resolve(ROOT, "web/src/styles/tokens.css"),
  type: resolve(ROOT, "web/src/styles/type.css"),
  kotlin: resolve(ROOT, "android/app/src/main/kotlin/dev/starbridge/app/ui/theme/Tokens.kt"),
};

type Role = {
  font: "sans" | "mono";
  size: number;
  weight: number;
  lineHeight: number;
  letterSpacing: number;
  uppercase?: boolean;
};
type Design = {
  colors: { light: Record<string, string>; dark: Record<string, string> };
  fonts: { sans: string; mono: string };
  typography: Record<string, Role>;
  spacing: Record<string, number>;
  radius: Record<string, number>;
  size: Record<string, number>;
  motion: Record<string, number>;
};

function load(): Design {
  const match = /^---\n([\s\S]*?)\n---\n/.exec(readFileSync(DESIGN_MD, "utf8"));
  if (!match) throw new Error("DESIGN.md: no YAML frontmatter");
  const design = Bun.YAML.parse(match[1]!) as Design;
  const { light, dark } = design.colors;
  for (const name of new Set([...Object.keys(light), ...Object.keys(dark)])) {
    for (const [scheme, colors] of [["light", light], ["dark", dark]] as const) {
      const value = colors[name];
      if (value === undefined) throw new Error(`colors.${scheme}.${name} is missing`);
      if (!/^#([0-9a-f]{6}|[0-9a-f]{8})$/i.test(value)) {
        throw new Error(`colors.${scheme}.${name}: ${value} is not #rrggbb or #rrggbbaa`);
      }
    }
  }
  for (const [name, role] of Object.entries(design.typography)) {
    if (!(role.font in design.fonts)) throw new Error(`typography.${name}: unknown font ${role.font}`);
  }
  return design;
}

const num = (n: number) => String(Number(n.toFixed(4)));

const GENERATED = [
  "GENERATED by web/scripts/tokens.ts from DESIGN.md. Do not edit;",
  "change the frontmatter and run `bun web/scripts/tokens.ts`.",
];
const CSS_HEADER = `/* ${GENERATED[0]}\n   ${GENERATED[1]} */\n`;
const KT_HEADER = `// ${GENERATED[0]}\n// ${GENERATED[1]}\n`;

function tokensCss(d: Design): string {
  const colors = (scheme: Record<string, string>, indent: string) =>
    Object.entries(scheme).map(([k, v]) => `${indent}--${k}: ${v};`);
  const px = (prefix: string, group: Record<string, number>) =>
    Object.entries(group).map(([k, v]) => `  --${prefix}${k}: ${num(v)}px;`);
  return [
    CSS_HEADER,
    ":root {",
    "  color-scheme: light dark;",
    ...colors(d.colors.light, "  "),
    "",
    ...px("", d.spacing),
    ...px("radius-", d.radius),
    ...px("size-", d.size),
    ...Object.entries(d.motion).map(([k, v]) => `  --t-${k}: ${v}ms;`),
    "}",
    "",
    "@media (prefers-color-scheme: dark) {",
    "  :root {",
    ...colors(d.colors.dark, "    "),
    "  }",
    "}",
    "",
  ].join("\n");
}

// --sans and --mono are bound to next/font's variables in app/layout.tsx.
function typeCss(d: Design): string {
  const lines = [CSS_HEADER];
  for (const [name, r] of Object.entries(d.typography)) {
    lines.push(`.t-${name} {`);
    lines.push(`  font-family: var(--${r.font});`);
    lines.push(`  font-size: ${num(r.size)}px;`);
    lines.push(`  font-weight: ${r.weight};`);
    lines.push(`  line-height: ${num(r.lineHeight)};`);
    lines.push(`  letter-spacing: ${num(r.letterSpacing)}em;`);
    if (r.uppercase) lines.push("  text-transform: uppercase;");
    if (r.font === "mono") lines.push("  font-variant-numeric: tabular-nums;");
    lines.push("}", "");
  }
  return lines.join("\n");
}

const camel = (key: string) => key.replace(/-(\w)/g, (_, c: string) => c.toUpperCase());

// #rrggbb[aa] -> Color(0xAARRGGBB)
function kColor(hex: string): string {
  const h = hex.slice(1).toUpperCase();
  const alpha = h.length === 8 ? h.slice(6) : "FF";
  return `Color(0x${alpha}${h.slice(0, 6)})`;
}

function tokensKt(d: Design): string {
  const names = Object.keys(d.colors.light);
  const scheme = (name: string, colors: Record<string, string>) => [
    `val ${name} = StarbridgeColors(`,
    ...names.map((k) => `    ${camel(k)} = ${kColor(colors[k]!)},`),
    ")",
    "",
  ];
  const dims = (name: string, group: Record<string, number>, unit: "dp" | "Long") => [
    `object ${name} {`,
    ...Object.entries(group).map(([k, v]) =>
      unit === "dp" ? `    val ${camel(k)} = ${num(v)}.dp` : `    const val ${camel(k)}Ms = ${v}L`,
    ),
    "}",
    "",
  ];
  const style = ([name, r]: [string, Role]) => {
    const fields = [
      `fontFamily = ${r.font},`,
      `fontSize = ${num(r.size)}.sp,`,
      `fontWeight = FontWeight(${r.weight}),`,
      `lineHeight = ${num(r.size * r.lineHeight)}.sp,`,
      `letterSpacing = ${num(r.letterSpacing)}.em,`,
    ];
    return [`    val ${camel(name)} = TextStyle(`, ...fields.map((f) => `        ${f}`), "    )"];
  };
  return [
    KT_HEADER,
    `package ${KOTLIN_PACKAGE}`,
    "",
    "import androidx.compose.runtime.Immutable",
    "import androidx.compose.ui.graphics.Color",
    "import androidx.compose.ui.text.TextStyle",
    "import androidx.compose.ui.text.font.FontFamily",
    "import androidx.compose.ui.text.font.FontWeight",
    "import androidx.compose.ui.unit.dp",
    "import androidx.compose.ui.unit.em",
    "import androidx.compose.ui.unit.sp",
    "",
    "@Immutable",
    "data class StarbridgeColors(",
    ...names.map((k) => `    val ${camel(k)}: Color,`),
    ")",
    "",
    ...scheme("LightColors", d.colors.light),
    ...scheme("DarkColors", d.colors.dark),
    ...dims("Spacing", d.spacing, "dp"),
    ...dims("Radius", d.radius, "dp"),
    ...dims("Sizes", d.size, "dp"),
    ...dims("Motion", d.motion, "Long"),
    "// The theme passes the bundled faces; uppercase roles set it at the call site:",
    `// ${Object.entries(d.typography)
      .filter(([, r]) => r.uppercase)
      .map(([n]) => camel(n))
      .join(", ")}.`,
    "class StarbridgeType(sans: FontFamily, mono: FontFamily) {",
    ...Object.entries(d.typography).flatMap(style),
    "}",
    "",
  ].join("\n");
}

const design = load();
const outputs: [string, string][] = [
  [OUT.css, tokensCss(design)],
  [OUT.type, typeCss(design)],
  [OUT.kotlin, tokensKt(design)],
];

if (process.argv.includes("--check")) {
  let stale = false;
  for (const [path, want] of outputs) {
    let have = "";
    try {
      have = readFileSync(path, "utf8");
    } catch {
      // missing counts as stale
    }
    if (have !== want) {
      stale = true;
      console.error(`${relative(ROOT, path)} is stale: run \`bun web/scripts/tokens.ts\``);
    }
  }
  process.exit(stale ? 1 : 0);
}

for (const [path, text] of outputs) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, text);
  console.log(`wrote ${relative(ROOT, path)}`);
}
